export const ANDROIDIOSMOBILEAPP_META = "ANDROIDIOSMOBILEAPP-META";
export const ANDROIDIOSMOBILEAPP_BDCMB = "ANDROIDIOSMOBILEAPP-BDCMB";
export const ANDROIDIOSMOBILEAPP_SLIDER = "ANDROIDIOSMOBILEAPP_SLIDER";
export const ANDROIDIOSMOBILEAPP_CTA = "ANDROIDIOSMOBILEAPP-CTA";


// QFIX 
export const QFIX_BDCMB = "QFIX-BDCMB";
export const QFIX_BANNER = "QFIX-BANNER"
export const QFIX_BRIEF = "QFIX-BRIEF"
export const QFIX_STATISTICK = "QFIX-STATISTICK"
export const QFIX_SERVICES_OFFER = "QFIX-SERVICES-OFFER"
export const QFIX_BUILD_PERFOMANCE = "QFIX-BUILD-PERFOMANCE"
export const QFIX_CUSTOMER_CHALLENGE = "QFIX-CUSTOMER-CHALLENGE"
export const QFIX_MOBILE_FEATURES = "QFIX-MOBILE-FEATURES"
export const QFIX_TECH_FEATURES = "QFIX-TECH-FEATURES"
export const QFIX_TECHNOLOGY_STACK = "QFIX-TECHNOLOGY-STACK"
export const QFIX_TC = "QFIX-TC"
export const QFIX_CASE_STUDY = "QFIX-CASE-STUDY"
export const PYTHON_NEWSLETTER = "PYTHON-NEWSLETTER"

// PCMC1
export const PCMC_BDCMB = "PCMC-BDCMB";
export const PCMC_BANNER = "PCMC-BANNER"
export const PCMC_BRIEF = "PCMC-BRIEF"
export const PCMC_STATISTICK = "PCMC-STATISTICK"
export const PCMC_SERVICES_OFFER = "PCMC-SERVICES-OFFER"
export const PCMC_BUILD_PERFOMANCE = "PCMC-BUILD-PERFOMANCE"
export const PCMC_CUSTOMER_CHALLENGE = "PCMC-CUSTOMER-CHALLENGE"
export const PCMC_DESKTOP_FEATURES = "PCMC-DESKTOP-FEATURES"
export const PCMC_TECH_FEATURES = "PCMC-TECH-FEATURES"
export const PCMC_TECHNOLOGY_STACK = "PCMC-TECHNOLOGY-STACK"
export const PCMC_TC = "PCMC-TC"
export const PCMC_CASE_STUDY = "PCMC-CASE-STUDY"

// PCMC2
export const PCMC2_BDCMB = "PCMC2-BDCMB";
export const PCMC2_BANNER = "PCMC2-BANNER"
export const PCMC2_BRIEF = "PCMC2-BRIEF"
export const PCMC2_STATISTICK = "PCMC2-STATISTICK"
export const PCMC2_SERVICES_OFFER = "PCMC2-SERVICES-OFFER"
export const PCMC2_BUILD_PERFOMANCE = "PCMC2-BUILD-PERFOMANCE"
export const PCMC2_CUSTOMER_CHALLENGE = "PCMC2-CUSTOMER-CHALLENGE"
export const PCMC2_MOBILE_FEATURES = "PCMC2-MOBILE-FEATURES"
export const PCMC2_TECH_FEATURES = "PCMC2-TECH-FEATURES"
export const PCMC2_TECHNOLOGY_STACK = "PCMC2-TECHNOLOGY-STACK"
export const PCMC2_TC = "PCMC2-TC"
export const PCMC2_CASE_STUDY = "PCMC2-CASE-STUDY"

// PCMC3
export const PCMC3_BDCMB = "PCMC3-BDCMB";
export const PCMC3_BANNER = "PCMC3-BANNER"
export const PCMC3_BRIEF = "PCMC3-BRIEF"
export const PCMC3_STATISTICK = "PCMC3-STATISTICK"
export const PCMC3_SERVICES_OFFER = "PCMC3-SERVICES-OFFER"
export const PCMC3_BUILD_PERFOMANCE = "PCMC3-BUILD-PERFOMANCE"
export const PCMC3_CUSTOMER_CHALLENGE = "PCMC3-CUSTOMER-CHALLENGE"
export const PCMC3_MOBILE_FEATURES = "PCMC3-MOBILE-FEATURES"
export const PCMC3_TECH_FEATURES = "PCMC3-TECH-FEATURES"
export const PCMC3_TECHNOLOGY_STACK = "PCMC3-TECHNOLOGY-STACK"
export const PCMC3_TC = "PCMC3-TC"
export const PCMC3_CASE_STUDY = "PCMC3-CASE-STUDY"

// PCMC4
export const PCMC4_BDCMB = "PCMC4-BDCMB";
export const PCMC4_BANNER = "PCMC4-BANNER"
export const PCMC4_BRIEF = "PCMC4-BRIEF"
export const PCMC4_STATISTICK = "PCMC4-STATISTICK"
export const PCMC4_SERVICES_OFFER = "PCMC4-SERVICES-OFFER"
export const PCMC4_BUILD_PERFOMANCE = "PCMC4-BUILD-PERFOMANCE"
export const PCMC4_CUSTOMER_CHALLENGE = "PCMC4-CUSTOMER-CHALLENGE"
export const PCMC4_MOBILE_FEATURES = "PCMC4-MOBILE-FEATURES"
export const PCMC4_TECH_FEATURES = "PCMC4-TECH-FEATURES"
export const PCMC4_TECHNOLOGY_STACK = "PCMC4-TECHNOLOGY-STACK"
export const PCMC4_TC = "PCMC4-TC"
export const PCMC4_CASE_STUDY = "PCMC4-CASE-STUDY"

// PCMC5
export const PCMC5_BDCMB = "PCMC5-BDCMB";
export const PCMC5_BANNER = "PCMC5-BANNER"
export const PCMC5_BRIEF = "PCMC5-BRIEF"
export const PCMC5_STATISTICK = "PCMC5-STATISTICK"
export const PCMC5_SERVICES_OFFER = "PCMC5-SERVICES-OFFER"
export const PCMC5_BUILD_PERFOMANCE = "PCMC5-BUILD-PERFOMANCE"
export const PCMC5_CUSTOMER_CHALLENGE = "PCMC5-CUSTOMER-CHALLENGE"

export const PCMC5_TECH_FEATURES = "PCMC5-TECH-FEATURES"
export const PCMC5_TECHNOLOGY_STACK = "PCMC5-TECHNOLOGY-STACK"
export const PCMC5_TC = "PCMC5-TC"
export const PCMC5_CASE_STUDY = "PCMC5-CASE-STUDY"

// ADERRO
export const ADERRO_BDCMB = "ADERRO-BDCMB";
export const ADERRO_BANNER = "ADERRO-BANNER"
export const ADERRO_BRIEF = "ADERRO-BRIEF"
export const ADERRO_STATISTICK = "ADERRO-STATISTICK"
export const ADERRO_SERVICES_OFFER = "ADERRO-SERVICES-OFFER"
export const ADERRO_BUILD_PERFOMANCE = "ADERRO-BUILD-PERFOMANCE"
export const ADERRO_CUSTOMER_CHALLENGE = "ADERRO-CUSTOMER-CHALLENGE"
export const ADERRO_MOBILE_FEATURES = "ADERRO-MOBILE-FEATURES"
export const ADERRO_TECH_FEATURES = "ADERRO-TECH-FEATURES"
export const ADERRO_TECHNOLOGY_STACK = "ADERRO-TECHNOLOGY-STACK"
export const ADERRO_TC = "ADERRO-TC"
export const ADERRO_CASE_STUDY = "ADERRO-CASE-STUDY"

// E3
export const E3_BDCMB = "E3-BDCMB";
export const E3_BANNER = "E3-BANNER"
export const E3_BRIEF = "E3-BRIEF"
export const E3_STATISTICK = "E3-STATISTICK"
export const E3_SERVICES_OFFER = "E3-SERVICES-OFFER"
export const E3_BUILD_PERFOMANCE = "E3-BUILD-PERFOMANCE"
export const E3_CUSTOMER_CHALLENGE = "E3-CUSTOMER-CHALLENGE"
export const E3_MOBILE_FEATURES = "E3-MOBILE-FEATURES"
export const E3_TECH_FEATURES = "E3-TECH-FEATURES"
export const E3_TECHNOLOGY_STACK = "E3-TECHNOLOGY-STACK"
export const E3_TC = "E3-TC"
export const E3_CASE_STUDY = "E3-CASE-STUDY"

// LEARNMARATHI
export const LEARNMARATHI_BDCMB = "LEARNMARATHI-BDCMB";
export const LEARNMARATHI_BANNER = "LEARNMARATHI-BANNER"
export const LEARNMARATHI_BRIEF = "LEARNMARATHI-BRIEF"
export const LEARNMARATHI_STATISTICK = "LEARNMARATHI-STATISTICK"
export const LEARNMARATHI_SERVICES_OFFER = "LEARNMARATHI-SERVICES-OFFER"
export const LEARNMARATHI_BUILD_PERFOMANCE = "LEARNMARATHI-BUILD-PERFOMANCE"
export const LEARNMARATHI_CUSTOMER_CHALLENGE = "LEARNMARATHI-CUSTOMER-CHALLENGE"
export const LEARNMARATHI_MOBILE_FEATURES = "LEARNMARATHI-MOBILE-FEATURES"
export const LEARNMARATHI_TECH_FEATURES = "LEARNMARATHI-TECH-FEATURES"
export const LEARNMARATHI_TECHNOLOGY_STACK = "LEARNMARATHI-TECHNOLOGY-STACK"
export const LEARNMARATHI_TC = "LEARNMARATHI-TC"
export const LEARNMARATHI_CASE_STUDY = "LEARNMARATHI-CASE-STUDY"

// WEMEDICO
export const WEMEDICO_BDCMB = "WEMEDICO-BDCMB";
export const WEMEDICO_BANNER = "WEMEDICO-BANNER"
export const WEMEDICO_BRIEF = "WEMEDICO-BRIEF"
export const WEMEDICO_STATISTICK = "WEMEDICO-STATISTICK"
export const WEMEDICO_SERVICES_OFFER = "WEMEDICO-SERVICES-OFFER"
export const WEMEDICO_BUILD_PERFOMANCE = "WEMEDICO-BUILD-PERFOMANCE"
export const WEMEDICO_CUSTOMER_CHALLENGE = "WEMEDICO-CUSTOMER-CHALLENGE"
export const WEMEDICO_MOBILE_FEATURES = "WEMEDICO-MOBILE-FEATURES"
export const WEMEDICO_TECH_FEATURES = "WEMEDICO-TECH-FEATURES"
export const WEMEDICO_TECHNOLOGY_STACK = "WEMEDICO-TECHNOLOGY-STACK"
export const WEMEDICO_TC = "WEMEDICO-TC"
export const WEMEDICO_CASE_STUDY = "WEMEDICO-CASE-STUDY"

// PMPL
export const PMPL_BDCMB = "PMPL-BDCMB";
export const PMPL_BANNER = "PMPL-BANNER"
export const PMPL_BRIEF = "PMPL-BRIEF"
export const PMPL_STATISTICK = "PMPL-STATISTICK"
export const PMPL_SERVICES_OFFER = "PMPL-SERVICES-OFFER"
export const PMPL_BUILD_PERFOMANCE = "PMPL-BUILD-PERFOMANCE"
export const PMPL_CUSTOMER_CHALLENGE = "PMPL-CUSTOMER-CHALLENGE"
export const PMPL_MOBILE_FEATURES = "PMPL-MOBILE-FEATURES"
export const PMPL_TECH_FEATURES = "PMPL-TECH-FEATURES"
export const PMPL_TECHNOLOGY_STACK = "PMPL-TECHNOLOGY-STACK"
export const PMPL_TC = "PMPL-TC"
export const PMPL_CASE_STUDY = "PMPL-CASE-STUDY"


// EZEEFINANZ
export const EZEEFINANZ_BDCMB = "EZEEFINANZ-BDCMB";
export const EZEEFINANZ_BANNER = "EZEEFINANZ-BANNER"
export const EZEEFINANZ_BRIEF = "EZEEFINANZ-BRIEF"
export const EZEEFINANZ_STATISTICK = "EZEEFINANZ-STATISTICK"
export const EZEEFINANZ_SERVICES_OFFER = "EZEEFINANZ-SERVICES-OFFER"
export const EZEEFINANZ_BUILD_PERFOMANCE = "EZEEFINANZ-BUILD-PERFOMANCE"
export const EZEEFINANZ_CUSTOMER_CHALLENGE = "EZEEFINANZ-CUSTOMER-CHALLENGE"
export const EZEEFINANZ_MOBILE_FEATURES = "EZEEFINANZ-MOBILE-FEATURES"
export const EZEEFINANZ_TECH_FEATURES = "EZEEFINANZ-TECH-FEATURES"
export const EZEEFINANZ_TECHNOLOGY_STACK = "EZEEFINANZ-TECHNOLOGY-STACK"
export const EZEEFINANZ_TC = "EZEEFINANZ-TC"
export const EZEEFINANZ_CASE_STUDY = "EZEEFINANZ-CASE-STUDY"


// EZEEFINANZ
export const AAPLESARKAR_BDCMB = "AAPLESARKAR-BDCMB";
export const AAPLESARKAR_BANNER = "AAPLESARKAR-BANNER"
export const AAPLESARKAR_BRIEF = "AAPLESARKAR-BRIEF"
export const AAPLESARKAR_STATISTICK = "AAPLESARKAR-STATISTICK"
export const AAPLESARKAR_SERVICES_OFFER = "AAPLESARKAR-SERVICES-OFFER"
export const AAPLESARKAR_BUILD_PERFOMANCE = "AAPLESARKAR-BUILD-PERFOMANCE"
export const AAPLESARKAR_CUSTOMER_CHALLENGE = "AAPLESARKAR-CUSTOMER-CHALLENGE"
export const AAPLESARKAR_MOBILE_FEATURES = "AAPLESARKAR-MOBILE-FEATURES"
export const AAPLESARKAR_TECH_FEATURES = "AAPLESARKAR-TECH-FEATURES"
export const AAPLESARKAR_TECHNOLOGY_STACK = "AAPLESARKAR-TECHNOLOGY-STACK"
export const AAPLESARKAR_TC = "AAPLESARKAR-TC"
export const AAPLESARKAR_CASE_STUDY = "AAPLESARKAR-CASE-STUDY"


// WTCMUMBAI
export const WTCMUMBAI_BDCMB = "WTCMUMBAI-BDCMB";
export const WTCMUMBAI_BANNER = "WTCMUMBAI-BANNER"
export const WTCMUMBAI_BRIEF = "WTCMUMBAI-BRIEF"
export const WTCMUMBAI_STATISTICK = "WTCMUMBAI-STATISTICK"
export const WTCMUMBAI_SERVICES_OFFER = "WTCMUMBAI-SERVICES-OFFER"
export const WTCMUMBAI_BUILD_PERFOMANCE = "WTCMUMBAI-BUILD-PERFOMANCE"
export const WTCMUMBAI_CUSTOMER_CHALLENGE = "WTCMUMBAI-CUSTOMER-CHALLENGE"
export const WTCMUMBAI_TECH_FEATURES = "WTCMUMBAI-TECH-FEATURES"
export const WTCMUMBAI_TECHNOLOGY_STACK = "WTCMUMBAI-TECHNOLOGY-STACK"
export const WTCMUMBAI_TC = "WTCMUMBAI-TC"
export const WTCMUMBAI_CASE_STUDY = "WTCMUMBAI-CASE-STUDY"

// FISSARA
export const FISSARA_BDCMB = "FISSARA-BDCMB";
export const FISSARA_BANNER = "FISSARA-BANNER"
export const FISSARA_BRIEF = "FISSARA-BRIEF"
export const FISSARA_STATISTICK = "FISSARA-STATISTICK"
export const FISSARA_SERVICES_OFFER = "FISSARA-SERVICES-OFFER"
export const FISSARA_BUILD_PERFOMANCE = "FISSARA-BUILD-PERFOMANCE"
export const FISSARA_CUSTOMER_CHALLENGE = "FISSARA-CUSTOMER-CHALLENGE"
export const FISSARA_MOBILE_FEATURES = "FISSARA-MOBILE-FEATURES"
export const FISSARA_TECH_FEATURES = "FISSARA-TECH-FEATURES"
export const FISSARA_TECHNOLOGY_STACK = "FISSARA-TECHNOLOGY-STACK"
export const FISSARA_TC = "FISSARA-TC"
export const FISSARA_CASE_STUDY = "FISSARA-CASE-STUDY"

// CARE
export const CARE_BDCMB = "CARE-BDCMB";
export const CARE_BANNER = "CARE-BANNER"
export const CARE_BRIEF = "CARE-BRIEF"
export const CARE_STATISTICK = "CARE-STATISTICK"
export const CARE_SERVICES_OFFER = "CARE-SERVICES-OFFER"
export const CARE_BUILD_PERFOMANCE = "CARE-BUILD-PERFOMANCE"
export const CARE_CUSTOMER_CHALLENGE = "CARE-CUSTOMER-CHALLENGE"
export const CARE_MOBILE_FEATURES = "CARE-MOBILE-FEATURES"
export const CARE_TECH_FEATURES = "CARE-TECH-FEATURES"
export const CARE_TECHNOLOGY_STACK = "CARE-TECHNOLOGY-STACK"
export const CARE_TC = "CARE-TC"
export const CARE_CASE_STUDY = "CARE-CASE-STUDY"

// WEBSCRAPING
export const WEBSCRAPING_BDCMB = "WEBSCRAPING-BDCMB";
export const WEBSCRAPING_BANNER = "WEBSCRAPING-BANNER"
export const WEBSCRAPING_BRIEF = "WEBSCRAPING-BRIEF"
export const WEBSCRAPING_STATISTICK = "WEBSCRAPING-STATISTICK"
export const WEBSCRAPING_SERVICES_OFFER = "WEBSCRAPING-SERVICES-OFFER"
export const WEBSCRAPING_BUILD_PERFOMANCE = "WEBSCRAPING-BUILD-PERFOMANCE"
export const WEBSCRAPING_CUSTOMER_CHALLENGE = "WEBSCRAPING-CUSTOMER-CHALLENGE"

export const WEBSCRAPING_TECH_FEATURES = "WEBSCRAPING-TECH-FEATURES"
export const WEBSCRAPING_TECHNOLOGY_STACK = "WEBSCRAPING-TECHNOLOGY-STACK"
export const WEBSCRAPING_TC = "WEBSCRAPING-TC"
export const WEBSCRAPING_CASE_STUDY = "WEBSCRAPING-CASE-STUDY"

// ISTIO
export const ISTIO_BDCMB = "ISTIO-BDCMB";
export const ISTIO_BANNER = "ISTIO-BANNER"
export const ISTIO_BRIEF = "ISTIO-BRIEF"
export const ISTIO_STATISTICK = "ISTIO-STATISTICK"
export const ISTIO_SERVICES_OFFER = "ISTIO-SERVICES-OFFER"
export const ISTIO_BUILD_PERFOMANCE = "ISTIO-BUILD-PERFOMANCE"
export const ISTIO_CUSTOMER_CHALLENGE = "ISTIO-CUSTOMER-CHALLENGE"

export const ISTIO_TECH_FEATURES = "ISTIO-TECH-FEATURES"
export const ISTIO_TECHNOLOGY_STACK = "ISTIO-TECHNOLOGY-STACK"
export const ISTIO_TC = "ISTIO-TC"
export const ISTIO_CASE_STUDY = "ISTIO-CASE-STUDY"

// EDUCATION 
export const EDUCATION_META = "EDUCATION_META"
export const EDUCATION_BDCMB = "EDUCATION-BDCMB"
export const EDUCATION_SLIDER = "EDUCATION_SLIDER"

// NEWS URL PREFIX
export const NEWS_URL_PREFIX = "v2stech-solutions-"

//Contact form types
export const CTA = 'cta'
export const NEWS_LETTER = 'news_letter'
export const CONTACT_FORM = 'contact_form'
export const HIRE_A_DEVELOPER = 'hire_a_developer_cta'
export const HIRING_MODEL = 'hiring_model'
export const FREE_EVALUATIONS = 'free_evaluation'